[[commands.file]]
name = "Open URL"
interpreter = "python"
script = "open_url.py"
extensions = ["url"]
args = []
clickable = true

[[commands.file]]
name = "Do something with Python"
interpreter = "python"
# relative to config file or absolute
script = "printargs.py"
extensions = ["py", "txt"]
args = []
